# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'GithubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for GithubApp
    pod 'AppCenter'
    pod 'RxSwift', '6.2.0'
   	pod 'RxCocoa', '6.2.0'
    pod 'Kingfisher', '~> 7.0'
    
  target 'GithubAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.2.0'
    pod 'RxTest', '6.2.0'
  end

  target 'GithubAppUITests' do
    # Pods for testing
  end

end
